import type { Config } from "tailwindcss";
import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "surface-tint": "#aad600",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c4c9ac",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#8e9379",
        "outline-variant": "#444933",
        primary: "#ffffff",
        "on-primary": "#283500",
        "primary-container": "#c3f400",
        "on-primary-container": "#556d00",
        "primary-fixed": "#c3f400",
        "primary-fixed-dim": "#aad600",
        "on-primary-fixed": "#161f00",
        "on-primary-fixed-variant": "#3c4d00",
        "inverse-primary": "#506600",
        secondary: "#cfcc3c",
        "on-secondary": "#333200",
        "secondary-container": "#a09d00",
        "on-secondary-container": "#343200",
        "secondary-fixed": "#ece856",
        "secondary-fixed-dim": "#cfcc3c",
        "on-secondary-fixed": "#1d1d00",
        "on-secondary-fixed-variant": "#4b4900",
        tertiary: "#ffffff",
        "on-tertiary": "#16343f",
        "tertiary-container": "#c8e7f6",
        "on-tertiary-container": "#4c6875",
        "tertiary-fixed": "#c8e7f6",
        "tertiary-fixed-dim": "#adcbda",
        "on-tertiary-fixed": "#001f29",
        "on-tertiary-fixed-variant": "#2e4b57",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      fontSize: {
        "display-xl": [
          "4.5rem",
          { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "800" },
        ],
        "headline-lg": [
          "2.25rem",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "title-md": [
          "1.25rem",
          { lineHeight: "1.5", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", fontWeight: "500" }],
        "label-xs": [
          "10px",
          { lineHeight: "1", letterSpacing: "0.4em", fontWeight: "900" },
        ],
      },
      fontFamily: {
        "display-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "label-xs": ["Plus Jakarta Sans"],
        "body-lg": ["Manrope"],
        "body-sm": ["Manrope"],
        headline: ["var(--font-plus-jakarta-sans)"],
        body: ["var(--font-manrope)"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "4rem",
        "stack-md": "2rem",
        "stack-sm": "1rem",
        gutter: "2rem",
        "section-padding": "6rem",
        "container-max": "80rem",
      },
      keyframes: {
        "bounce-slow": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "bounce-slow-reverse": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(10px)" },
        },
      },
      animation: {
        "bounce-slow": "bounce-slow 5s ease-in-out infinite",
        "bounce-slow-reverse": "bounce-slow-reverse 6s ease-in-out infinite",
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
